app:
  name: My App
  description: Welcome to ${app.name}

my:
  greeting: hello
  list:
    value: one,two,three,four

db:
  connection: test-connection-string-here
  host: 129.0.0.1
  port: 2400

management.endpoints.web.exposure.include: "*"
